workflows:
  ios-workflow:
    name: Build BatzenOS
    environment:
      xcode: latest
    scripts:
      - name: Build .ipa
        script: |
          xcodebuild -project BatzenOS.xcodeproj -scheme BatzenOS -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Build/BatzenOS.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Build/BatzenOS.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/Build/BatzenOS
    artifacts:
      - Build/BatzenOS/*.ipa
